#!/bin/bash

usage()
{
cat << EOF
Usage: $0 [options]

Options:
  -s    Start the dev server.
  -o    Open the default browser on the entry page.
  -d    Deploy.. sync changes to live server.
  -h    Show this help message and exit.

EOF
}

while getopts "dohs" OPTION
do
    case $OPTION in
        o)
            open http://localhost:8000/
            exit
            ;;
        s)
            #python -m CGIHTTPServer 8000
            #/usr/local/bin/php -S localhost:8000 -t public/
            http-server public -p 8000
            exit
            ;;
        d)
            #rsync -av --delete public/ -e ssh user@example.com:docroot/
            exit
            ;;
        h)
            usage
            exit 1
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done
